# This is a basic workflow to help you get started with Actions
name: pytest 

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Create mock API keys to avoid errors
      - name: Create Mock API keys
        run: |
          touch backend/backend/.env
          echo "NTA_DEVELOPER_KEY=ABC" > backend/backend/.env
          echo "AWS_MYSQL_PASSWORD=ABC" >> backend/backend/.env
          echo "LOCAL_MYSQL_PASSWORD=ABC" >> backend/backend/.env

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      - name: Install Dependencies
        run: pip install -r requirements.txt

      # --check returns 0 if there's no modifications needed or 1 if there's failed tests
      - name: Run pytest
        run: python -m pytest
